spring.application.name=MrcConfigServer

server.port=1111
spring.cloud.config.server.git.uri=https://github.com/cipher39/spring_properties

# By default, Spring Cloud Config Server tries to read from the main branch.
# If your Git repository's default branch is master (or something else), you'll get:
# NoSuchLabelException: No such label: main
spring.cloud.config.server.git.default-label=master